language: node_js
node_js:
  - "4.3.1"
  - "0.10"
script: make test-coverage
after_success:
  - './node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info'
addons:
  code_climate:
    repo_token: baed462671bc79d6ec0d9d57be57ced36fa4b3ae499672199da8536e99676cde
